

# Word2Vec (According to Your Notes)

### Definition

> Word2Vec is a neural network-based word embedding technique developed by Google (2013) that converts words into dense vectors while capturing semantic relationships between words. 

>**Word2Vec** is a neural network-based technique that converts words into dense numerical vectors (embeddings) while preserving semantic and contextual relationships between words.

---

## Why Word2Vec?

Previous techniques:

```text
One Hot Encoding
↓
Bag of Words
↓
TF-IDF
```

Problems:

* Sparse matrix
* No semantic meaning
* Large vocabulary size
* OOV (Out Of Vocabulary) issues

Word2Vec solves these by learning **dense vector representations**. 

---

## Word Embedding

Word → Dense Vector

```text
King  → [-0.92, 0.95, 0.97, ...]
Queen → [ 0.93, 0.96, 0.68, ...]
```

Words with similar meanings are located closer in vector space. 

---

## Types of Word2Vec

### 1. CBOW (Continuous Bag of Words)

Predict target word from surrounding context.

```text
Context Words
      ↓
     CBOW
      ↓
Target Word
```

Example:

```text
Infosys Company Related To Data Science

Input:
Infosys, Company, Related, To

Output:
IS
```

CBOW works better on smaller datasets. 

---

### 2. Skip-Gram

Predict surrounding words from target word.

```text
Target Word
      ↓
   Skip-Gram
      ↓
Context Words
```

Example:

```text
Input:
IS

Output:
Infosys, Company, Related, To
```

Skip-Gram performs better on large datasets. 

---

## Window Size

Defines how many neighboring words are considered.

Example:

```text
Infosys Company Related To Data Science

Window Size = 2
```

For word:

```text
Related
```

Context:

```text
Company, Related, To
```

Increasing window size generally improves contextual understanding but increases training complexity. 

---

## Feature Representation

Word2Vec learns features automatically:

```text
King
↓
Gender
Royal
Age
Food
...
```

Instead of manually creating features. 

---

## Semantic Relationships

Word2Vec can perform vector arithmetic:

```text
King - Man + Woman = Queen
```

or

```text
King - Boy + Girl = Queen
```

This shows semantic information is captured in embeddings. 

---

## Cosine Similarity

Measures similarity between two vectors.

Formula:

\cos(\theta)=\frac{A\cdot B}{|A||B|}

Interpretation:

```text
1   → Exactly Similar
0   → Unrelated
-1  → Opposite
```

Used extensively with Word2Vec. 

---

## Advantages

* Dense matrix instead of sparse matrix
* Captures semantic meaning
* Fixed dimensional representation (e.g., 300 dimensions)
* Similar words are placed close together
* Better than BoW and TF-IDF for semantic tasks 

---

# Average Word2Vec

### Problem

Word2Vec gives vectors for individual words.

Example:

```text
The food is good
```

Need one vector for the entire sentence/document.

---

## Solution: Average Word2Vec

Take the average of all word vectors.

```text
Word Vectors
      ↓
Average
      ↓
Sentence Vector
```

Example:

```text
The food is good
```

```text
The   → Vector1
food  → Vector2
is    → Vector3
good  → Vector4
```

Average:

```text
(Vector1 + Vector2 + Vector3 + Vector4) / 4
```

Result:

```text
300-Dimensional Document Vector
```

This single vector can be fed into ML algorithms. 

---

## Workflow

```text
Text
 ↓
Pretrained Word2Vec (Google/Gensim)
 ↓
Word Embeddings
 ↓
Average All Vectors
 ↓
Document Vector
 ↓
Machine Learning Model
```

---

## Why Use Average Word2Vec?

* Fixed-size representation
* Better semantic representation than BoW
* Easy to implement
* Works well for classification tasks

---

## One-Line Interview Answers

### Word2Vec

> Word2Vec is a neural-network-based word embedding technique that learns dense vector representations of words by analyzing their context.

### CBOW

> CBOW predicts a target word from surrounding context words.

### Skip-Gram

> Skip-Gram predicts surrounding context words from a target word.

### Average Word2Vec

> Average Word2Vec creates a document-level embedding by averaging all Word2Vec vectors in a sentence or document.

 


In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 50.6 MB/s eta 0:00:00


In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
import gensim.downloader as api

wv_model = api.load("word2vec-google-news-300")



[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [4]:
# convert any word into 300 dimension vectors

vec_king = wv_model.word_vec("king")
vec_queen = wv_model.word_vec("queen")
vec_diff = vec_king - vec_queen
vec_diff

/tmp/ipykernel_17096/4069902826.py:3: DeprecationWarning: Call to deprecated `word_vec` (Use get_vector instead).
  vec_king = wv_model.word_vec("king")
/tmp/ipykernel_17096/4069902826.py:4: DeprecationWarning: Call to deprecated `word_vec` (Use get_vector instead).
  vec_queen = wv_model.word_vec("queen")


array([ 1.20727539e-01,  1.73339844e-01,  7.79418945e-02,  1.61132812e-02,
       -1.57470703e-01,  5.27343750e-02,  1.83105469e-01,  1.85546875e-02,
        2.48535156e-01,  3.07617188e-01, -1.66503906e-01,  7.81250000e-02,
       -2.81738281e-01, -2.40859985e-02, -3.00781250e-01, -2.82714844e-01,
       -3.80859375e-02,  5.20935059e-02, -1.95312500e-02,  3.46679688e-02,
       -5.37109375e-02, -2.39257812e-02,  2.95898438e-01,  2.55371094e-01,
        3.56445312e-02, -1.23535156e-01,  5.66406250e-02, -3.19824219e-02,
        1.53320312e-01,  1.35864258e-01,  2.60742188e-01,  1.92626953e-01,
        2.07031250e-01,  1.87500000e-01,  3.32031250e-02,  2.15820312e-01,
       -5.71289062e-02, -2.57812500e-01,  1.65039062e-01, -1.07421875e-02,
        3.17382812e-02,  1.84570312e-01,  1.36718750e-02,  1.70288086e-01,
        1.66015625e-01,  8.88671875e-02, -1.05743408e-01, -1.12304688e-01,
       -2.10937500e-01, -2.52258301e-01, -1.44165039e-01,  5.95703125e-02,
       -3.12744141e-01,  

In [16]:
wv_model.most_similar([vec_diff])

[('king', 0.375265508890152),
 ('P._Calamos', 0.2744928300380707),
 ('Sultan', 0.26501351594924927),
 ('---_Sammy_Sugiura', 0.2511763870716095),
 ('Qudah', 0.25087296962738037),
 ('al_Houthi', 0.24859227240085602),
 ('Mokthar', 0.24822978675365448),
 ('Kaf', 0.24637752771377563),
 ('Buster_Mathis', 0.24622151255607605),
 ('Robert_Coyiuto', 0.24591834843158722)]

In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
vec_man = wv_model["man"]
vec_man

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [8]:
wv_model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [10]:
wv_model.similarity("man","woman")

np.float32(0.76640123)

In [11]:
wv_model.most_similar("happy")

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [12]:
wv_model.similarity("football","sports")

np.float32(0.5927178)

In [14]:
vec = wv_model["king"]-wv_model["man"]+wv_model["woman"]
print(vec)


[ 4.29687500e-02 -1.78222656e-01 -1.29089355e-01  1.15234375e-01
  2.68554688e-03 -1.02294922e-01  1.95800781e-01 -1.79504395e-01
  1.95312500e-02  4.09919739e-01 -3.68164062e-01 -3.96484375e-01
 -1.56738281e-01  1.46484375e-03 -9.30175781e-02 -1.16455078e-01
 -5.51757812e-02 -1.07574463e-01  7.91015625e-02  1.98974609e-01
  2.38525391e-01  6.34002686e-02 -2.17285156e-02  0.00000000e+00
  4.72412109e-02 -2.17773438e-01 -3.44726562e-01  6.37207031e-02
  3.16406250e-01 -1.97631836e-01  8.59375000e-02 -8.11767578e-02
 -3.71093750e-02  3.15551758e-01 -3.41796875e-01 -4.68750000e-02
  9.76562500e-02  8.39843750e-02 -9.71679688e-02  5.17578125e-02
 -5.00488281e-02 -2.20947266e-01  2.29492188e-01  1.26403809e-01
  2.49023438e-01  2.09960938e-02 -1.09863281e-01  5.81054688e-02
 -3.35693359e-02  1.29577637e-01  2.41699219e-02  3.48129272e-02
 -2.60009766e-01  2.42309570e-01 -3.21777344e-01  1.45416260e-02
 -1.59179688e-01 -8.37402344e-02  1.65039062e-01  1.58691406e-03
  3.09570312e-01  3.16406

In [15]:
wv_model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [ ]:
# avgword2vec 

import numpy as np

def avg_word2vec(words, model):

    vectors = [
        model[word]
        for word in words
        if word in model
    ]

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

avg_word2vec("I love nlp".split(),wv_model)